# 应用程序配置
app:
  debug: true
  host: "0.0.0.0"
  port: 5000

# 火山引擎配置
volc:
  access_key: "9UwX560SkTVpQVXV-1Uwok6tcQWPOt8U"
  secret_key: "pVC9Yfy8NyUO-3uRajGviQ_u0K8ZjZyj"
  app_id: "4673284572"
  cluster: "volcengine_input_common"

# 其他配置项
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"